export CC=clang
export CXX=clang++

cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=PowerPC \
    -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF \
    -DCMAKE_RANLIB=llvm-ranlib -DCMAKE_AR=llvm-ar -DLLVM_USE_LINKER=lld \
    -DLLVM_DEFAULT_TARGET_TRIPLE=powerpc-eabi -DLLVM_ENABLE_LTO=Thin \
    -DLLVM_OPTIMIZED_TABLEGEN=ON -DCLANG_ENABLE_ARCMT=OFF -DCLANG_PLUGIN_SUPPORT=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_BUILD_TOOLS=OFF -DCLANG_BUILD_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF \
    -DCLANG_ENABLE_STATIC_ANALYZER=OFF -DLLVM_ENABLE_ZSTD=OFF -DLLVM_ENABLE_ZLIB=OFF -DLLVM_ENABLE_LIBXML2=OFF -DCLANG_ENABLE_OBJC_REWRITER=OFF \
    -DCMAKE_C_FLAGS="-ffile-prefix-map=$(pwd)=/build -ffile-prefix-map=$HOME=/root -faddrsig"\
    -DCMAKE_CXX_FLAGS="-ffile-prefix-map=$(pwd)=/build -ffile-prefix-map=$HOME=/root -faddrsig" \
    -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -Wl,-mllvm,-thinlto-assume-merged -Wl,-S -Wl,--strip-all -Wl,--gc-sections -Wl,--icf=safe"
