cmake -S llvm -B build -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=PowerPC \
	-DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DCLANG_INCLUDE_TESTS=OFF \
	-DLLVM_DEFAULT_TARGET_TRIPLE=powerpc-eabi -DLLVM_ENABLE_LTO=Full \
	-DLLVM_OPTIMIZED_TABLEGEN=ON -DCLANG_ENABLE_ARCMT=OFF -DCLANG_PLUGIN_SUPPORT=OFF -DLLVM_ENABLE_BINDINGS=OFF -DLLVM_BUILD_TOOLS=OFF -DCLANG_BUILD_TOOLS=OFF -DLLVM_INCLUDE_UTILS=OFF \
	-DCLANG_ENABLE_STATIC_ANALYZER=OFF -DLLVM_ENABLE_ZSTD=OFF -DLLVM_ENABLE_ZLIB=OFF -DLLVM_ENABLE_LIBXML2=OFF -DCLANG_ENABLE_OBJC_REWRITER=OFF \
	-DCMAKE_C_FLAGS="-ffile-prefix-map=$(pwd)=/build -ffile-prefix-map=$HOME=/root" \
	-DCMAKE_CXX_FLAGS="-ffile-prefix-map=$(pwd)=/build -ffile-prefix-map=$HOME=/root" \
	-DCMAKE_EXE_LINKER_FLAGS="-Wl,-mllvm,-thinlto-assume-merged -Wl,-S -Wl,-x -Wl,-dead_strip -Wl, -reproducible" \
	-DCMAKE_OSX_ARCHITECTURES=x86_64 -DLLVM_ENABLE_TERMINFO=OFF
